CREATE TABLE USER(

  ID TEXT PRIMARY KEY NOT NULL ,
  PASSWORD TEXT NOT NULL ,
  HEAD BLOB ,

  HISTORY_ORDER BLOB ,
  PRESENT_ORDER BLOB ,

  DC BLOB ,  -- discount card
  AP INTEGER NOT NULL ,  -- accumulate points

  DRIVERS BLOBl
);



CREATE TABLE DRIVER(

  ID TEXT PRIMARY KEY NOT NULL ,
  PASSWORD TEXT NOT NULL ,

  HISTORY_ORDER BLOB,
  PRESENT_ORDER BLOB
);



CREATE TABLE "ORDER"(

  ID TEXT PRIMARY KEY NOT NULL ,
  USERNAME TEXT NOT NULL ,
  DRIVERNAME TEXT NOT NULL ,
  START_TIME REAL  NOT NULL ,
  END_TIME REAL ,
  REMARK TEXT
);

