CREATE TABLE USER(

  ID INTEGER PRIMARY KEY ,
  USERNAME TEXT NOT NULL ,
  PASSWORD TEXT NOT NULL ,
  HEAD BLOB ,

  HISTORY_ORDER BLOB ,
  PRESENT_ORDER BLOB ,

  DC BLOB ,  -- discount card
  AP INTEGER ,  -- accumulate points

  DRIVERS BLOB
);



CREATE TABLE DRIVER(

  ID INTEGER PRIMARY KEY ,
  DRIVERNAME TEXT NOT NULL ,
  PASSWORD TEXT NOT NULL ,

  HISTORY_ORDER BLOB,
  PRESENT_ORDER BLOB
);



CREATE TABLE "ORDER"(

  ID INTEGER PRIMARY KEY ,
  USERID INTEGER NOT NULL ,
  DRIVERNAME INTEGER NOT NULL ,
  START_TIME REAL  NOT NULL ,
  END_TIME REAL ,
  REMARK TEXT
);

